# 内置Tomcat配置
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
    max-http-header-size: 10000000
    max-http-post-size: -1
  connection-timeout: 5000ms
  port: 8089
  servlet:
    context-path: /
    session:
      cookie:
        http-only: true